### PR TITLE
Drop optional flake inputs

### PR DESCRIPTION
**Pull request by SuperSandro2000**

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Sadly this only works on unstable, not stable....

**Comment by MarcelCoding** [comment]
How would you now override these transient inputs? This was the reason we've put them in the first place.

**Comment by SuperSandro2000** [comment]
They are not required for the module or the package, only for local development. So you don't because we don't need them.

**Review by MarcelCoding — APPROVED** [review]

**Comment by MarcelCoding** [comment]
nvm i am blind

**Pull request merged**
