### PR TITLE
More random things

### PR DESCRIPTION
**Pull request by SuperSandro2000**

### CODE REVIEW

**Review by MarcelCoding — COMMENTED** [review]
What does the code in this section do? Does it replaces last place?

**Comment by SuperSandro2000** [comment]
Which section?

**Comment by MarcelCoding** [comment]
default.nix starting at line 18


... GitHub on android does not place the comments to the line I've selected

**Comment by SuperSandro2000** [comment]
Ups, that's duplicated

**Review by MarcelCoding — APPROVED** [review]

**Comment by SuperSandro2000** [comment]
I fixed some more cmp things:
- wrong arg
- don't return completion when pressing Return and no entry is selected

**Pull request merged**
