### PR TITLE
lsp: remove typos-lsp

### PR DESCRIPTION
**Pull request by SuperSandro2000**

### CODE REVIEW

**Comment by MarcelCoding** [comment]
Does anyone you that bad?

**Comment by SuperSandro2000** [comment]
I had that laying around, but I am not sure anymore why tbh. Maybe it was also texlab.

**Comment by MarcelCoding** [comment]
We removed ltexls a few PRs earlier.

**Comment by SuperSandro2000** [comment]
Then I probably messed that up

**Pull request closed without merging**
